### ISSUE TITLE
Keep flows desynchronized during congestion

### ISSUE THREAD

**Issue by rscheff** [ietf-wg-ccwg/rfc5033bis#11] opened 2023-02-24 13:06 UTC
When queue saturation happens, aim to keep CC reaction desynchronized as much as possible - with tail drop this is not really possible, but AQM especially with ECN may be able to do this.

**Comment by huitema** [comment] 2023-08-26 05:17
@rscheff should we make recommendations for AQM in this document? I don't think we can, but I may be wrong. Of course we could consider some kind of randomization by the end points, but do we have examples of implementations?

**Comment by martinduke** [comment] 2023-10-16 15:22
Related to #7

**Comment by Ealdwulf** [comment] 2023-10-23 11:25
There was GSP: https://datatracker.ietf.org/doc/html/draft-lauten-aqm-gsp-03 , but I don't know if it ever got implemented in the wild

**Comment by huitema** [comment] 2023-11-07 09:31
Matt made a good point about synchronization being caused by protocols "testing against queue full". Synchronization happens when all connections sharing the same protocol experience the same feedback signal at the same time. They indeed will if the queue has filled up completely, and all connections suddenly experience a high "packet loss" signal. But there may be other scenarios. For example, if an transmission line breaks, all connections will experience it. And if they all try to recover with the same timing, we will see a "thundering herd" when the link break is repaired.

**Comment by martinduke** [comment] 2023-12-13 21:19
I think I agree with @huitema's original point here. AQM design is not in scope of this document, and purely endpoint-based approaches to this problem are bleeding-edge at best.

A proposal that did this would hopefully get "bonus points" somehow, but I believe this is covered under the general heading of "how well does this proposal compete with itself?"

**Comment by martinduke** [comment] 2023-12-15 16:39
Closing this with no action, as existing criteria cover it as describe above.

**Closed by martinduke** 2023-12-15 16:39 UTC
